#!/usr/bin/env python3
"""Generate every derived asset Fumobooru's HTML needs.

The gallery draws previews at --size (120-270px) and the post view at up to
76vh, but the sources in fumos/ run to 3072x4096 / 2.2MB, so both were pulling
the full file. For every post this writes:

    thumbs/<name>.webp   grid preview, THUMB_H px tall
    mids/<name>.webp     post view, MID_W px wide; the post view links to the
                         untouched original for anything larger
    card.jpg             1200x630 Open Graph card for social embeds
    p/<id>.html          per-post OG stub that redirects to /#post/<id>

It also recomputes site.posts / site.tags and the og:image in index.html,
strips metadata from the originals, and deletes anything in thumbs/, mids/ or
p/ that no post points at any more.

Idempotent: a derived file is rebuilt only when the source is newer than the
recipe that made it, so a re-run is cheap and replacing a source image under
the same filename does rebuild. Changing a size or quality changes the recipe
and forces one full rebuild.

    python3 make-thumbs.py            # defaults: 300px thumbs, 1600px mids
    python3 make-thumbs.py 540        # true 2x thumbs for the 270px grid size
    python3 make-thumbs.py 540 1200   # ... and 1200px mids
"""
import html
import json
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent
THUMBS = ROOT / "thumbs"
MIDS = ROOT / "mids"
PAGES = ROOT / "p"
DATA = ROOT / "fumosData.js"
INDEX = ROOT / "index.html"
CARD = "card.jpg"

# Crawlers and og:image both need absolute URLs, and this is now the only
# place the deploy domain is written down: index.html's tags are rewritten
# from it on every run.
SITE_URL = "https://fumobooru.vercel.app"

THUMB_H = int(sys.argv[1]) if len(sys.argv) > 1 else 300
MID_W = int(sys.argv[2]) if len(sys.argv) > 2 else 1600
QUALITY = 80
METHOD = 6

# The webp encoder, its settings and the auto-orient/strip pair, as one string.
# A mismatch against what a post already has means "rebuild me".
THUMB_RECIPE = f"auto-orient strip fit{THUMB_H} webp q{QUALITY} m{METHOD}"
MID_RECIPE = f"auto-orient strip fit{MID_W} webp q{QUALITY} m{METHOD}"

# Nearly half the sources are small, heavily-compressed JPEGs that a q80 webp
# cannot beat: the "mid" would be 7x the bytes of the thing it replaces. Those
# posts keep their original and record why, instead of shipping a file the
# post view would never read.
NO_MID = "no mid: "

HEADER = (
    "// Post data. Images live in ./fumos and are referenced with relative paths,\n"
    "// so the site works from file:// and from any Vercel subpath.\n"
    "// Generated by make-thumbs.py — edit that, not this.\n"
)

# A post stub is what makes a per-post link preview work on a static host: a
# crawler fetching /p/901001.html never sees the #post/901001 hash, so this
# has to be a real document. The refresh and the script both send the visitor
# on to the real thing.
STUB = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<link rel="canonical" href="{url}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="Fumobooru">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{image}">
<meta property="og:image:type" content="image/jpeg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="{alt}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image" content="{image}">
<meta name="theme-color" content="#0e1015">
<meta http-equiv="refresh" content="0; url=../#post/{id}">
<link rel="stylesheet" href="../style.css">
</head>
<body>
<p>Taking you to <a href="../#post/{id}">post {id}</a>&hellip;</p>
<script>location.replace("../#post/{id}")</script>
</body>
</html>
"""


def run(*args):
    subprocess.run(args, check=True)


def read_data():
    raw = DATA.read_text()
    return json.loads(re.search(r"window\.FUMO_DATA = (.*);\s*$", raw, re.S).group(1))


def stage(src, post, td):
    """A still ImageMagick can read: video posts get a frame pulled first."""
    if post["type"] != "video":
        return f"{src}[0]"
    frame = pathlib.Path(td) / "frame.png"
    # ~1s in, past any fade-in
    run("ffmpeg", "-y", "-loglevel", "error", "-ss", "1", "-i", str(src),
        "-vframes", "1", str(frame))
    return str(frame)


def render(still, out, geometry):
    # -auto-orient has to come first: orientation is only recorded in EXIF, and
    # -strip on the next line throws that away, so a phone photo that merely
    # says "rotate me" would otherwise come out sideways. -strip is also what
    # keeps GPS out of every file this site hands out.
    run("magick", still, "-auto-orient", "-strip", "-resize", geometry,
        "-quality", str(QUALITY), "-define", f"webp:method={METHOD}", str(out))


def stale(out, post, recipe_field, recipe, mtime):
    """Rebuild unless this exact recipe already ran against this exact source.

    A recorded NO_MID is a decision, not a gap: it means the source beat the
    mid on bytes (or is a video), and it is only re-decided once the source
    itself changes.
    """
    state = post.get(recipe_field)
    if post.get("srcMtime") != mtime:
        return True
    if isinstance(state, str) and state.startswith(NO_MID):
        return out.exists()  # a leftover file from an earlier run
    return state != recipe or not out.exists()


def sweep(directory, keep):
    """Delete anything in a generated directory that no post points at."""
    dropped = 0
    for f in sorted(directory.iterdir()):
        if f.is_file() and f.name not in keep:
            print(f"  orphan {f.relative_to(ROOT)}")
            f.unlink()
            dropped += 1
    return dropped


def strip_originals():
    """Drop metadata from the sources in fumos/.

    Anything shot on a phone can carry a GPS trail, and these files are served
    in the clear to anyone. exiftool is preferred because it edits in place
    without re-encoding; ImageMagick is the fallback. ICC is deliberately kept
    — it is a colour profile, not a location, and dropping it shifts colours.
    """
    victims = []
    for f in sorted((ROOT / "fumos").iterdir()):
        if not f.is_file():
            continue
        # reads empty for anything ImageMagick cannot open, which just means
        # "leave it alone"
        profiles = subprocess.run(
            ["magick", "identify", "-format", "%[profiles]", str(f)],
            capture_output=True, text=True).stdout.lower()
        if {"exif", "iptc", "xmp", "8bim"} & set(profiles.split()):
            victims.append(f)
    if not victims:
        print("  originals already clean (no exif/iptc/xmp)")
        return
    if shutil.which("exiftool"):
        run("exiftool", "-all=", "-overwrite_original", "-q", *[str(f) for f in victims])
    else:
        for f in victims:
            run("magick", "mogrify", "-strip", str(f))
    print(f"  stripped metadata from {len(victims)} original(s)")


def make_card(posts, site):
    """A 1200x630 Open Graph card: the highest-scoring photo cropped to fill,
    with the brand over a scrim. Discord, Slack, Facebook and Twitter all want
    at least this, and the old og:image was a raw 720x540 photo of some dolls.
    """
    cover = max((p for p in posts if p["type"] == "image"), key=lambda p: p["score"])
    run("magick", f"{ROOT / cover['src']}[0]",
        "-auto-orient", "-resize", "1200x630^",
        "-gravity", "center", "-extent", "1200x630",
        "-strip",
        "-fill", "rgba(14,16,21,0.68)", "-draw", "rectangle 0,436 1200,630",
        "-font", "Be-Vietnam-Pro-Bold", "-pointsize", "50", "-fill", "#e8c15a",
        "-gravity", "southwest", "-annotate", "+40+92", site["name"],
        "-pointsize", "23", "-fill", "#dfe3ec",
        "-annotate", "+40+40", site["tagline"],
        "-quality", "88", str(ROOT / CARD))
    site["socialImage"] = CARD
    return cover


def tags_of(post):
    return [t for group in post["tags"].values() for t in group]


def human(n):
    return f"{n/1024/1024:.1f} MB" if n >= 1024 * 1024 else f"{n//1024} KB"


def write_stubs(posts):
    image = f"{SITE_URL}/{CARD}"
    for post in posts:
        tags = tags_of(post)
        title = f"{', '.join(tags[:4])} — Fumobooru"
        PAGES.joinpath(f"{post['id']}.html").write_text(STUB.format(
            id=post["id"],
            url=f"{SITE_URL}/p/{post['id']}.html",
            image=image,
            title=html.escape(title),
            # crawlers truncate, so lead with the tags and cap the length
            desc=html.escape(f"Post #{post['id']}: {', '.join(tags)}."[:200]),
            alt=html.escape(", ".join(tags[:3]).replace("_", " ")),
        ))


def set_meta(markup, value, attr, kind="property"):
    """Rewrite one <meta ... content="..."> in index.html, anchors included."""
    return re.sub(rf'(<meta {kind}="{re.escape(attr)}" content=")[^"]*(")',
                  lambda m: m.group(1) + value + m.group(2), markup)


def patch_index(site, cover, n_photos):
    """index.html is hand-written prose, so only the numbers and the image
    URLs are owned here. Anything unmatched is a silent lie, so check."""
    markup = INDEX.read_text()
    markup = re.sub(r"\d+ photos of Touhou", f"{n_photos} photos of Touhou", markup)
    url = f"{SITE_URL}/{CARD}"
    for kind, attr, value in (
        ("property", "og:image", url),
        ("property", "og:image:type", "image/jpeg"),
        ("property", "og:image:width", "1200"),
        ("property", "og:image:height", "630"),
        ("property", "og:image:alt", ", ".join(tags_of(cover)[:3]).replace("_", " ").capitalize()),
        ("name", "twitter:image", url),
    ):
        markup = set_meta(markup, value, attr, kind)
    if f"{n_photos} photos" not in markup or url not in markup:
        raise SystemExit("index.html no longer has the expected OG tags; "
                         "update set_meta() by hand")
    INDEX.write_text(markup)


def main():
    data = read_data()
    site, posts = data["site"], data["posts"]
    for d in (THUMBS, MIDS, PAGES):
        d.mkdir(exist_ok=True)

    strip_originals()

    made, reused, kept = 0, 0, 0
    for post in posts:
        name = pathlib.Path(post["src"]).stem
        src = ROOT / post["src"]
        thumb, mid = THUMBS / f"{name}.webp", MIDS / f"{name}.webp"
        post["thumb"] = f"thumbs/{name}.webp"
        # superseded by the recipe string, which says the same thing
        post.pop("thumb_height", None)
        post.pop("mid", None)
        post.pop("midBytes", None)

        if not src.exists():
            print(f"  MISSING {post['src']}")
            for field in ("thumbRecipe", "srcMtime", "thumbBytes"):
                post.pop(field, None)
            continue

        # milliseconds, so an edit inside the same second still counts
        mtime = round(src.stat().st_mtime * 1000)
        todo = []
        if stale(thumb, post, "thumbRecipe", THUMB_RECIPE, mtime):
            todo.append((thumb, f"{THUMB_H}x{THUMB_H}"))
        if stale(mid, post, "midRecipe", MID_RECIPE, mtime):
            if post["type"] != "video":
                # width-only, so a tall photo is not silently squeezed by a
                # square box the way the grid thumbnails are
                todo.append((mid, f"{MID_W}x"))

        if todo:
            with tempfile.TemporaryDirectory() as td:
                still = stage(src, post, td)
                for out, geometry in todo:
                    render(still, out, geometry)
            made += len(todo)
        else:
            reused += 1

        post["srcMtime"] = mtime
        post["srcBytes"] = src.stat().st_size
        # the sidebar shows this, and it drifted the moment the originals were
        # stripped, so it is measured here rather than written by hand
        post["fileSize"] = human(post["srcBytes"])
        post["thumbBytes"] = thumb.stat().st_size
        post["thumbRecipe"] = THUMB_RECIPE
        if post["type"] == "video":
            post["midRecipe"] = NO_MID + "video"
            mid.unlink(missing_ok=True)
        elif mid.exists() and mid.stat().st_size < src.stat().st_size:
            post["mid"] = f"mids/{name}.webp"
            post["midBytes"] = mid.stat().st_size
            post["midRecipe"] = MID_RECIPE
        else:
            mid.unlink(missing_ok=True)
            post["midRecipe"] = NO_MID + "source is already smaller"
            kept += 1

    names = {f"{pathlib.Path(p['src']).stem}.webp" for p in posts}
    orphans = sweep(THUMBS, names) + sweep(MIDS, names)
    orphans += sweep(PAGES, {f"{p['id']}.html" for p in posts})

    cover = make_card(posts, site)
    write_stubs(posts)

    # nothing else should be hand-editing these
    all_tags = {t for p in posts for t in tags_of(p)}
    site["posts"] = len(posts)
    site["tags"] = len(all_tags)
    site["artists"] = len({t for p in posts for t in p["tags"].get("artist", [])})
    patch_index(site, cover, len([p for p in posts if p["type"] == "image"]))

    DATA.write_text(HEADER + "window.FUMO_DATA = " + json.dumps(data, indent=2) + ";\n")

    def total(field):
        return sum(p.get(field) or 0 for p in posts)

    print(f"thumbs {THUMB_H}px, mids {MID_W}px, webp q{QUALITY} method {METHOD}")
    print(f"  wrote {made}, reused {reused}, deleted {orphans} orphan(s)")
    print(f"  {len(posts)} posts, {len(all_tags)} tags, {len(list(PAGES.glob('*.html')))} stubs")
    for label, field in (("sources", "srcBytes"), ("thumbs", "thumbBytes"), ("mids", "midBytes")):
        mb = total(field) / 1024 / 1024
        print(f"  {label:8} {mb:6.1f} MB")
    # what a post view actually costs: the mid where there is one, the
    # untouched source where there is not
    viewed = sum(p["midBytes"] if p.get("mid") else p["srcBytes"] for p in posts)
    print(f"  {len(posts) - kept} posts view a mid, {kept} keep an already-tiny source")
    print(f"  post view: {total('srcBytes')/1024/1024:.1f} MB -> {viewed/1024/1024:.1f} MB")


if __name__ == "__main__":
    main()
